# Generated by Django 2.2.2 on 2019-07-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='personcomment',
            new_name='add_comment',
        ),
    ]
